classDiagram
direction TB
    class Difficulty {
        -combatWaves : EntityWave[]
        -currentWave : int
        +getAllWaves()
        +getNextWave()
        +addCombatWave()
        +removeCombatWave()
    }

    class Easy {
        -combatWaves : EntityWave[]
        -currentWave : int
    }

    class Medium {
        -combatWaves : EntityWave[]
        -currentWave : int
    }

    class Hard {
        -combatWaves : EntityWave[]
        -currentWave : int
    }

    class Entities {
        -playerControl : boolean
        -ongoingSpecialStatus : SpecialStatus[]
        +action()
    }

    class PlayerClass {
        -playerControl : boolean
        -bag : ItemBag
        -startingNumOfItems : int
        -specialSkillName : String
        -specialSkillCD : int
        +useItem()
        +gainItem()
        +loseItem()
        +defend()
        +specialSkill(EnemyType)
        +getSpecialSkillCD()
        +getSpecialSkillName()
        +setSpecialSkillCD()
        +action()
    }

    class EnemyType {
        -playerControl : boolean
        +action()
    }

    class HPAttribute {
        -hp : int
        -curHP : int
        +getHP()
        +setHP()
        +changeHP()
    }

    class AttackAttribute {
        -attack : int
        +getAttack()
        +setAttack()
        +changeAttack()
    }

    class DefenceAttribute {
        -defence : int
        +getDefence()
        +setDefence()
        +changeDefence()
    }

    class SpeedAttribute {
        -speed : int
        +getSpeed()
        +setSpeed()
        +changeSpeed()
    }

    class IsAlive {
        -aliveStatus : boolean
        +getAliveStatus()
        +setAliveStatus()
    }

    class Warrior {
        -hp : HPAttribute
        -attack : AttackAttribute
        -defence : DefenceAttribute
        -speed : SpeedAttribute
        -startingNumOfItems : int
        -specialSkillName : String
        -specialSkillCD : int
        +specialSkill(EnemyType)
        +action()
    }

    class Wizard {
        -hp : HPAttribute
        -attack : AttackAttribute
        -defence : DefenceAttribute
        -speed : SpeedAttribute
        -startingNumOfItems : int
        -specialSkillName : String
        -specialSkillCD : int
        +specialSkill(EnemyType)
        +action()
    }

    class Goblin {
        -hp : HPAttribute
        -attack : AttackAttribute
        -defence : DefenceAttribute
        -speed : SpeedAttribute
        +action()
    }

    class Wolf {
        -hp : HPAttribute
        -attack : AttackAttribute
        -defence : DefenceAttribute
        -speed : SpeedAttribute
        +action()
    }

    class SpecialStatus {
        -statusName : String
        -statusDuration : int
        -curStatusDuration : int
        -effectedEntity : Entities
        -priority : int
        -hpModifier : HPModifier
        -attackModifier : AttackModifier
        -defenceModifier : DefenceModifier
        -speedModifier : SpeedModifier
        -incomingDamageModifier : IncomingDamageModifier
        -outcomingDamageModifier : OutgoingDamageModifier
        +onHit()
        +onStartTurn()
        +onAllStartTurn()
        +onStartRound()
        +onEndTurn()
        +onAllEndTurn()
        +onEndRound()
        +onDeath()
        +onExpire()
        +onInfliction()
        +getStatusDuration()
        +getCurStatusDuration()
        +changeCurStatusDuration()
        +displayMessage()
    }

    class ArcaneBlast {
        -statusName : String
        -statusDuration : int
        -curStatusDuration : int
        -effectedEntity : Entities
        -priority : int
        +onInfliction()
        +getStatusDuration()
        +getCurStatusDuration()
        +changeCurStatusDuration()
    }

    class Stun {
        -statusName : String
        -statusDuration : int
        -curStatusDuration : int
        -effectedEntity : Entities
        -priority : int
        +onEndTurn()
        +onExpire()
        +onInfliction()
        +getStatusDuration()
        +getCurStatusDuration()
        +changeCurStatusDuration()
    }

    class Defend {
        -statusName : String
        -statusDuration : int
        -curStatusDuration : int
        -effectedEntity : Entities
        -priority : int
        +onEndTurn()
        +onExpire()
        +onInfliction()
        +getStatusDuration()
        +getCurStatusDuration()
        +changeCurStatusDuration()
    }

    class SmokeBombStatus {
        -statusName : String
        -statusDuration : int
        -curStatusDuration : int
        -effectedEntity : Entities
        -priority : int
        -outgoingDamageMultiplier : double
        +onEndTurn()
        +onExpire()
        +onInfliction()
        +getStatusDuration()
        +getCurStatusDuration()
        +changeCurStatusDuration()
    }

    class Item {
        <<abstract>>
        -itemName : String
        -itemQuantity : int
        -perishable : boolean
        +getQuantity()
        +setQuantity()
        +useTarget()
        +itemEffect()
    }

    class Potion {
        -itemName : String
        -itemQuantity : int
        -perishable : boolean
        +getQuantity()
        +setQuantity()
        +useTarget()
        +itemEffect()
    }

    class Powerstone {
        -itemName : String
        -itemQuantity : int
        -perishable : boolean
        +getQuantity()
        +setQuantity()
        +useTarget()
        +itemEffect()
    }

    class SmokeBombItem {
        -itemName : String
        -itemQuantity : int
        -perishable : boolean
        +getQuantity()
        +setQuantity()
        +useTarget()
        +itemEffect()
    }

    Item <|-- Potion
    Item <|-- Powerstone
    Item <|-- SmokeBombItem

    class DamageCalculator {
        -attacker : Combatant
        -defender : Combatant[]
        -baseDamage : int
        -finalDamage : int
        +calculateDamage()
        +applyDefence()
        +applyIncomingModifiers()
        +executeDamage()
        +executeOnHit()
        +updateAliveStatus()
    }

    class Combatant {
        <<abstract>>
        -hp : HPAttribute
        -attack : AttackAttribute
        -defence : DefenceAttribute
        -speed : SpeedAttribute
        -ongoingSpecialStatus : SpecialStatus[]
        -aliveStatus : IsAlive
        -hasPermission : Permission
        -triggers : LocalTriggers
        +basicAttack()
        +calculateEffectiveHP()
        +calculateEffectiveAttack()
        +calculateEffectiveDefence()
        +calculateEffectiveSpeed()
        +calculateEffectiveStats()
    }

    Combatant <|-- PlayerClass
    Combatant <|-- EnemyType

    class ItemBag {
        -capacity : int
        -storage : Item[]
        -owner : Combatant
        +getCapacity()
        +setCapacity()
        +gainItem()
        +loseItem()
        +useItem()
    }

    class SpeedTracker {
        -turnOrder : Combatant[]
        -currTurnOrder : Combatant
        +updateTurnOrder()
        +updateCurrTurnOrder()
        +getTurnOrder()
        +getCurrTurnOrder()
        +removeFromTurnOrder()
        +removeFromCurrTurnOrder()
        +addToCurrTurnOrder()
        +addToTurnOrder()
    }

    class CombatEncounter {
        -difficultyWaves : Difficulty
        -turnOrder : SpeedTracker
        +startRound()
        +endRound()
        +startTurn()
        +endTurn()
        +updateAliveStatus()
        +checkBackup()
        +deployBackup()
        +checkGameState()
        +combatEnd()
    }

    class EntityWave {
        -allCharacters : Combatant[]
        -numOfCharacters : int
        -waveNum : int
        +addToWave()
        +removeFromWave()
        +getWave()
        +getNumOfCharacters()
        +setNumOfCharacters()
        +getWaveNum()
        +setWaveNum()
    }

    class HPModifier {
        -hpModifier : int
        +getHPModifier()
        +setHPModifier()
        +modifyHP(hitpoints : int)
    }

    class AttackModifier {
        -attackModifier : int
        +getAttackModifier()
        +setAttackModifier()
        +modifyAttack(attack : int)
    }

    class DefenceModifier {
        -defenceModifier : int
        +getDefenceModifier()
        +setDefenceModifier()
        +modifierDefence(defence : int)
    }

    class SpeedModifier {
        -speedModifier : int
        +getSpeedModifier()
        +setSpeedModifier()
        +modifySpeed(speed : int)
    }

    class IncomingDamageModifier {
        -incomingDamageModifier : int
        +getIncomingDamageModifier()
        +setIncomingDamageModifier()
        +modifyIncomingDamageModifier(damage : int)
    }

    class OutgoingDamageModifier {
        -outgoingDamageModifier : int
        +getOutgoingDamageModifier()
        +setOutgoingDamageModifier()
        +modifyOutgoingDamageModifier(damage : int)
    }

    class Permissions {
        -canAct : boolean
        -canAttack : boolean
        -canDefend : boolean
        -canUseItem : boolean
        +getCanAct()
        +setCanAct()
        +getCanAttack()
        +setCanAttack()
        +getCanDefend()
        +setCanDefend()
        +getCanUseItem()
        +setCanUseItem()
    }

    class TargetGetter {
        -targets : Combatant[]
        +typeFilter()
        +getTarget()
    }

    class LocalTriggers {
        -localTriggerList : Map<LocalTriggerTypes, SpecialStatus[]>
        +getLocalTrigger(LocalTriggerTypes type)
        +addLocalTrigger(LocalTriggerTypes type, SpecialStatus status)
        +removeLocalTrigger(LocalTriggerTypes type, SpecialStatus status)
    }

    class LocalTriggerTypes {
        <<enumeration>>
        ON_ATTACK
        ON_GETTING_ATTACKED
        ON_DEATH
        ON_KILL
        ON_START_TURN
        ON_END_TURN
    }

    class GlobalTriggers {
        -globalTriggerList : Map<GlobalTriggerTypes, SpecialStatus[]>
        +getGlobalTrigger(GlobalTriggerTypes type)
        +addGlobalTrigger(GlobalTriggerTypes type, SpecialStatus status)
        +removeGlobalTrigger(GlobalTriggerTypes type, SpecialStatus status)
    }

    class GlobalTriggerTypes {
        <<enumeration>>
        ON_START_ROUND
        ON_END_ROUND
    }

    <<interface>> Difficulty
    <<interface>> Entities
    <<abstract>> PlayerClass
    <<abstract>> EnemyType
    <<abstract>> SpecialStatus

    SpecialStatus <|-- ArcaneBlast
    SpecialStatus <|-- Stun
    SpecialStatus <|-- Defend
    SpecialStatus <|-- SmokeBombStatus
    Difficulty <|.. Easy
    Difficulty <|.. Medium
    Difficulty <|.. Hard
    Entities <|.. Combatant
    PlayerClass <|-- Warrior
    PlayerClass <|-- Wizard
    EnemyType <|-- Goblin
    EnemyType <|-- Wolf
